### ISSUE TITLE
Use publicsuffix crate to check suffixes

### ISSUE THREAD

**Issue by erickt** [pfernie/user_agent#2]
I wanted to give you a heads up that someone's implemented a [publicsuffix crate](https://crates.io/crates/publicsuffix), and a [publicsuffix crate cache](https://crates.io/crates/psl), so it might be pretty simple to get this integrated.

**Comment by pfernie** [comment]
I landed changes implementing initial support for public suffixes via `publicsuffix` crate. Note that I did not implement tests for public suffix cases; I will be opening some other issues to track this.
