### ISSUE TITLE
Not possible to use rustls-tls with user_agent

### ISSUE THREAD

**Issue by colemickens** [pfernie/user_agent#24]
I had previously been using `reqwest` in such a way that I had purely Rust code and didn't need a C compiler and/or openssl.

Now that I've switched to `user_agent`, this no longer is possible. I think that it may require work in `user_agent`, `cookie_store` and `publicsuffix`, since `publicsuffix` seems to be the culprit pulling openssl into the fray.

**Comment by pfernie** [comment]
We don't actually use the `remote_list` functionality presented in `publicsuffix` which was bringing in the `openssl` dependency, so `cookie_store` has been updated to simply disable the default features. `user_agent` has also been updated to introduce a `default-tls` and `rustls-tls` feature to parallels' `reqwest`'s  features, as the default features there pull in `native-tls`/`openssl` as well.

Updating and building with `--no-default-features --features="rustls-tls"` should therefore switch the downstream dependencies and avoid pulling in `openssl`.

**Comment by colemickens** [comment]
Thank you very much for resolvng this!
